using BulkInsertAPI.Data.DbContexts;
using BulkInsertAPI.Services.Helpers.Model;
using Microsoft.EntityFrameworkCore;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BulkInsertAPI.Services.Helpers.Builders;

public interface IBulkInsertBinaryStatementBuilder<T> where T : class
{
    public BulkCopyBinaryStatements GetStatements();
}

//TODO: use LazyCache or similar to cache the results and avoid using statics in a scoped class
[System.Diagnostics.CodeAnalysis.SuppressMessage("Critical Code Smell", "S2696:Instance members should not write to \"static\" fields", Justification = "<Pending>")]
public class BulkInsertBinaryStatementBuilder<T> : IBulkInsertBinaryStatementBuilder<T> where T: class
{
    private readonly ApplicationDbContext _applicationDbContext;

    private static readonly object _lock = new();
    private static bool _isInitialized = false;

    private static string _tableName = default!;
    private static string[] _pkColumnNames = default!;
    private static List<string> _insertablePropertyNames = default!;

    private static string _createTempTableSqlStatement = default!;
    private static string _copyBinarySqlStatement = default!;
    private static string _insertTempTableSqlStatement = default!;
    private static string _dropTempTableSqlStatement = default!;

    private const string TempPrefix = "temp";

    public BulkInsertBinaryStatementBuilder(ApplicationDbContext applicationDbContext)
    {
        _applicationDbContext = applicationDbContext;
    }

    private void EnsureInitialized()
    {
        if (!_isInitialized)
        {
            lock (_lock)
            {
                if (!_isInitialized)
                {
                    Init();
                    _isInitialized = true;
                }
            }
        }

    }

    private void Init()
    {
        InitEntityTypeRelatedInfo();

        _createTempTableSqlStatement = GetCreateTempTableSqlStatement();
        _copyBinarySqlStatement = GetCopyBinaryStatement();
        _insertTempTableSqlStatement = GetInsertStatement();
        _dropTempTableSqlStatement = GetDropTempTableSqlStatement();
        
    }

    private void InitEntityTypeRelatedInfo()
    {
        // Create an instance of the DbContext
        var entityType = _applicationDbContext.Model.GetEntityTypes().FirstOrDefault(et => et.ClrType == typeof(T)) 
            ?? throw new ArgumentException($"Invalid entity type provided (not a db context type): {TypeName}");

        // Be aware that this only works for public (schema) tables
        _tableName = entityType.GetTableName()
            ?? throw new ArgumentException($"Failed to find table name for the type {TypeName}");

        _pkColumnNames = entityType.FindPrimaryKey()?.Properties?.Select(p => p.GetColumnName()).ToArray()
            ?? throw new ArgumentException($"Failed to find primary key for the type {TypeName}");

        var _autogeneratedColumnNames = entityType.GetProperties()
            .Where(p => p.GetValueGenerationStrategy() != NpgsqlValueGenerationStrategy.None)
            .Select(p => p.GetColumnName())
            .ToList();
        var propertyNames = typeof(T).GetProperties().Select(x => x.Name).ToList();
        _insertablePropertyNames = propertyNames.Except(_autogeneratedColumnNames).ToList();
    }

    private static string TypeName => typeof(T).Name;

    public string GetTempTableName() => TempPrefix + '_' + TypeName.ToLower();

    private string GetCreateTempTableSqlStatement()
    {
        string tempTableName = GetTempTableName();
        return $@"CREATE TEMP TABLE {tempTableName} AS TABLE ""{TypeName}"" WITH NO DATA;";
    }

    private string GetDropTempTableSqlStatement()
    {
        string tempTableName = GetTempTableName();
        return $@"DROP TABLE IF EXISTS {tempTableName};";
    }

    private string GetCopyBinaryStatement()
    {
        string tempTableName = GetTempTableName();
        var columnsStr = "\"" + string.Join("\", \"", _insertablePropertyNames) + "\"";

        return $"COPY {tempTableName} ({columnsStr}) FROM STDIN (FORMAT BINARY)";
    }

    private string GetInsertStatement()
    {
        string tempTableName = GetTempTableName();
        var columnStr = "\"" + string.Join("\", \"", _insertablePropertyNames) + "\"";
        var uniquenessColumns = "\"" + string.Join("\", \"", _pkColumnNames) + "\"";

        // Be aware that this only works for public (schema) tables, as it double quotes the table name
        string query = $$"""
INSERT INTO "{{_tableName}}"
({{columnStr}})
SELECT {{columnStr}}
FROM {{tempTableName}}
ON CONFLICT ({{uniquenessColumns}}) DO NOTHING;
""";
        return query;
    }


    public BulkCopyBinaryStatements GetStatements()
    {
        EnsureInitialized();

        return new BulkCopyBinaryStatements
        {
            CreateTempTableSqlStatement = _createTempTableSqlStatement,
            CopyBinarySqlStatement = _copyBinarySqlStatement,
            InsertTempTableSqlStatement = _insertTempTableSqlStatement,
            DropTempTableSqlStatement = _dropTempTableSqlStatement
        };
    }
}

